#!/bin/sh
VERSION="$1"
shift
COMMAND="$@"

if [ -z "$DOCKER_PLENV_IMAGE" ]; then
  DOCKER_PLENV_IMAGE=miyagawa/plenv
fi

docker run -e PLENV_VERSION=$VERSION $DOCKER_PLENV_IMAGE bash -c ". /root/.plenv.sh; plenv $COMMAND"
